### ISSUE TITLE
打开音频文件报错：Unknown audio format 0x3 in wav data

### ISSUE THREAD

**Issue by yichengsd** [code-killerr/Auto_Cut_Audio#1]
不识别音频格式，如何处理

>>> auto_cut_audio.auto_cut_audio(r'D:\Audio5\5_01.wav')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Python311\Lib\site-packages\auto_cut_audio-0.0.2-py3.11.egg\auto_cut_audio\auto_cut_audio.py", line 15, in auto_cut_audio
  File "D:\Python\Python311\Lib\site-packages\auto_cut_audio-0.0.2-py3.11.egg\auto_cut_audio\HandleAudio.py", line 52, in __init__
  File "D:\Python\Python311\Lib\site-packages\auto_cut_audio-0.0.2-py3.11.egg\auto_cut_audio\HandleAudio.py", line 273, in __decodeFmt__
Exception: 
[5_01.zip](https://github.com/code-killerr/Auto_Cut_Audio/files/12668110/5_01.zip)

**Comment by code-killerr** [comment]
目前只支持01的pcm编码，你这个编码格式我看一下能不能兼容

**Comment by code-killerr** [comment]
已经优化

**Comment by yichengsd** [comment]
非常感谢，已经可以工作了。
